<a href="https://colab.research.google.com/github/justinbkeeler/useful_python/blob/main/Uploading_Data_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Option 1: Load local data into Google Colab

In [7]:
# Load libraries
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

# Optional io syntax
import io

Saving titanic.xlsx to titanic.xlsx

In [4]:
df = pd.read_excel("titanic.xlsx")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Option 2: Loading data from a cloud repo (e.g. GitHub, OSF, Kaggle) into Google Colab

In [8]:
# Load libraries
import pandas as pd

In [9]:
url = "https://raw.githubusercontent.com/justinbkeeler/Datasets/main/titanic.csv"
df2 = pd.read_csv(url)
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Option 3a: Loading data from a Google Drive into Google Colab

In [21]:
# View the current working directory
!pwd

/content

In [22]:
!ls

content  drive	sample_data  titanic.xlsx

In [24]:
!ls "/content/drive/My Drive/"

'Colab CO 2023'		    'Evaluations - Student (OBU)'  'Remote Worker Project'
'Colab Notebooks'	     Grants			    Sandbox
'Conference Presentations'  'Guest Speaker'		   'TCU Faculty Presentation'
'Course Material'	     Posters			   'Unpublished Research'
'Course Syllabi'	    'Press Releases'		    Workshops
'Curriculum Vitae'	     Publications

In [25]:
!ls "/content/drive/My Drive/Sandbox"

 iris.csv	    'litbooks (2).csv'	'litbooks (6).csv'   titanic.csv       usedcarsUSA.csv
'laptops (1).csv'   'litbooks (3).csv'	 litbooks.csv	     titanic.xlsx
 laptops.csv	    'litbooks (4).csv'	 nflcombine.xlsx     toughsport.csv
'litbooks (1).csv'  'litbooks (5).csv'	 salestarget.csv     toughsport.xlsx

In [26]:
# Map to '_______' folder within '_____________' folder within 'My Drive' folder
dataset_path = "/content/drive/My Drive/Sandbox"

In [27]:
print(dataset_path)

/content/drive/My Drive/Sandbox

In [28]:
# To use the dataset_path, you need to update it to include the .csv file
dataset_path = "/content/drive/My Drive/Sandbox/usedcarsUSA.csv"

# Load the CSV file into a DataFrame
df3 = pd.read_csv(dataset_path)

# Display the DataFrame
df3

,Unnamed: 0,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,0,6300,toyota,cruiser,2008,clean vehicle,274117.0,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,1,2899,ford,se,2011,clean vehicle,190552.0,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,2,5350,dodge,mpv,2018,clean vehicle,39590.0,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,3,25000,ford,door,2014,clean vehicle,64146.0,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,4,27700,chevrolet,1500,2018,clean vehicle,6654.0,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2494,7800,nissan,versa,2019,clean vehicle,23609.0,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,2495,9200,nissan,versa,2018,clean vehicle,34553.0,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,2496,9200,nissan,versa,2018,clean vehicle,31594.0,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,2497,9200,nissan,versa,2018,clean vehicle,32557.0,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,2498,9200,nissan,versa,2018,clean vehicle,31371.0,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

In [29]:
df3.describe()

        Unnamed: 0         price         year       mileage           lot
count  2499.000000   2499.000000  2499.000000  2.499000e+03  2.499000e+03
mean   1249.000000  18767.671469  2016.714286  5.229869e+04  1.676914e+08
std     721.543484  12116.094936     3.442656  5.970552e+04  2.038772e+05
min       0.000000      0.000000  1973.000000  0.000000e+00  1.593488e+08
25%     624.500000  10200.000000  2016.000000  2.146650e+04  1.676253e+08
50%    1249.000000  16900.000000  2018.000000  3.536500e+04  1.677451e+08
75%    1873.500000  25555.500000  2019.000000  6.347250e+04  1.677798e+08
max    2498.000000  84900.000000  2020.000000  1.017936e+06  1.678055e+08

Option 3b: Map to a specific folder within Google Drive (beyond the default /content)

In [30]:
# Import the os library
import os

In [31]:
# Get the current working directoy
os.getcwd()

'/content'

In [32]:
# Change to a different folder using "os.chdir"
path_to_mydataset = "/content/drive/My Drive/Sandbox"
os.chdir(path_to_mydataset)

In [33]:
# Confirm a directory remapping to a different folder
os.getcwd()

'/content/drive/My Drive/Sandbox'

In [34]:
# View list of files with "!ls" in the mapped destination
!ls

 iris.csv	    'litbooks (2).csv'	'litbooks (6).csv'   titanic.csv       usedcarsUSA.csv
'laptops (1).csv'   'litbooks (3).csv'	 litbooks.csv	     titanic.xlsx
 laptops.csv	    'litbooks (4).csv'	 nflcombine.xlsx     toughsport.csv
'litbooks (1).csv'  'litbooks (5).csv'	 salestarget.csv     toughsport.xlsx

In [35]:
df5 = pd.read_csv("toughsport.csv")
df5

,SPORT,END,STR,PWR,SPD,AGI,FLX,NER,DUR,HAN,ANA,TOTAL,RANK
0,Boxing,8.63,8.13,8.63,6.38,6.25,4.38,8.88,8.50,7.00,5.63,72.375,1
1,Ice Hockey,7.25,7.13,7.88,7.75,7.63,4.88,6.00,8.25,7.50,7.50,71.750,2
2,Football,5.38,8.63,8.13,7.13,6.38,4.38,7.25,8.50,5.50,7.13,68.375,3
3,Basketball,7.38,6.25,6.50,7.25,8.13,5.63,4.13,7.75,7.50,7.38,67.875,4
4,Wrestling,6.63,8.38,7.13,5.13,6.38,7.50,5.00,6.75,4.25,6.38,63.500,5
5,Martial Arts,5.00,5.88,7.75,6.38,6.00,7.00,6.63,5.88,6.00,6.88,63.375,6
6,Tennis,7.25,5.13,7.13,6.75,7.75,5.63,3.00,5.00,8.38,6.75,62.750,7
7,Gymnastics,5.38,6.13,6.63,5.00,6.38,10.00,7.50,6.88,4.50,4.13,62.500,8
8,Baseball/Softball,4.63,5.75,7.63,6.50,6.75,4.75,5.13,5.63,9.25,6.25,62.250,9
9,Soccer,7.75,4.50,5.13,7.25,8.25,4.75,3.63,6.25,6.50,7.50,61.500,10
10,Skiing: Alpine,5.13,5.25,6.00,7.38,6.13,5.63,8.38,6.00,5.13,5.63,60.625,11
11,Water Polo,7.88,6.63,6.88,5.38,6.38,5.00,4.25,6.38,6.25,5.63,60.625,11
12,Rugby,6.75,7.00,6.38,5.88,6.00,4.13,6.50,7.88,4.38,5.63,60.500,13
13,Lacrosse,6.63,5.13,5.75,7.00,6.63,4.75,4.38,6.13,7.13,6.88,60.375,14
14,Rodeo: Steer Wrestling,4.00,7.00,7.88,3.88,4.88,5.00,7.88,6.88,5.13,4.00,56.500,15
15,Track and Field: Pole Vault,3.38,6.88,7.25,6.13,5.38,7.00,6.63,4.25,5.25,3.75,55.875,16
16,Field Hockey,6.75,4.50,5.38,6.00,5.75,4.63,3.75,5.00,6.63,6.50,54.875,17
17,Speed Skating,7.63,7.25,7.38,8.88,4.00,4.25,4.50,4.63,2.88,3.50,54.875,17
18,Figure Skating,6.38,5.25,6.63,5.13,6.88,8.25,4.88,4.00,3.13,4.25,54.750,19
19,Cycling: Distance,9.63,6.38,6.25,5.13,3.75,2.63,5.88,6.88,3.00,4.88,54.375,20
20,Volleyball,5.13,4.88,6.63,5.00,7.00,5.13,2.88,4.63,7.25,5.88,54.375,20
21,Racquetball/Squash,6.13,3.75,5.00,5.50,7.25,5.88,2.38,2.88,8.38,6.50,53.625,22
22,Surfing,4.63,5.00,4.13,4.25,6.63,5.50,8.25,5.50,4.38,4.88,53.125,23
23,Fencing,4.63,3.75,4.25,5.13,6.13,5.63,4.88,4.25,7.25,6.88,52.750,24
24,Skiing: Freestyle,4.13,5.13,4.88,5.13,6.63,6.88,6.63,5.13,4.13,3.88,52.500,25
25,Team Handball,4.88,3.88,5.38,5.50,6.00,4.50,3.00,3.88,7.88,5.88,50.750,26
26,Cycling: Sprints,4.25,6.13,7.88,7.50,4.00,2.88,4.75,4.50,3.63,4.50,50.000,27
27,Bobsledding/Luge,3.50,5.50,6.50,6.75,4.13,3.25,7.75,3.50,4.13,4.25,49.250,28
28,Ski Jumping,3.50,4.50,5.75,4.63,4.00,5.00,9.00,4.63,4.38,3.50,48.875,29
29,Badminton,5.25,3.25,4.00,5.63,7.38,5.25,1.25,2.63,7.25,6.13,48.000,30
30,Skiing: Nordic,9.00,5.75,4.38,5.13,4.00,4.00,2.75,5.50,3.63,3.88,48.000,30
31,Auto Racing,5.88,3.50,2.63,1.63,2.75,1.75,9.88,4.38,8.00,7.50,47.875,32
32,Track and Field: High Jump,3.00,6.00,7.00,6.13,5.63,6.63,3.50,3.50,3.50,2.88,47.750,33
33,"Track and Field: Long, Triple jumps",4.00,5.63,7.13,6.75,5.00,5.75,2.75,3.25,4.00,3.13,47.375,34
34,Diving,2.88,5.13,4.63,3.00,3.50,8.50,8.38,5.00,3.00,3.00,47.000,35
35,Swimming (all strokes): Distance,9.25,5.25,4.63,5.50,3.63,5.50,2.63,4.63,2.88,3.00,46.875,36
36,Skateboarding,4.13,3.75,3.75,4.13,6.13,5.13,6.50,5.25,4.88,3.13,46.750,37
37,Track and Field: Sprints,3.50,5.13,7.25,9.88,4.63,5.13,2.00,4.13,2.63,2.38,46.625,38
38,Rowing,8.13,7.75,7.13,4.00,2.50,4.00,1.75,4.38,2.88,3.63,46.125,39
39,Rodeo: Calf Roping,3.13,5.38,5.00,4.25,5.63,3.88,4.88,3.75,6.38,3.75,46.000,40
40,Track and Field: Distance,9.63,5.25,3.75,6.00,3.25,4.38,2.00,5.75,1.88,4.13,46.000,40
41,Rodeo: Bull/Bareback/Bronc Riding,3.25,5.38,4.00,1.75,3.63,4.25,9.50,7.38,3.63,3.13,45.875,42
42,Track and Field: Middle Distance,6.00,5.13,5.13,7.75,4.00,4.88,2.00,4.75,2.13,3.75,45.500,43
43,Weight-Lifting,4.13,9.25,9.75,2.63,2.50,3.38,4.00,4.75,2.25,2.38,45.000,44
44,Swimming (all strokes): Sprints,4.13,5.25,6.25,7.88,3.63,5.50,2.50,3.25,2.75,3.00,44.125,45
45,Water Skiing,4.63,5.00,4.50,3.00,4.25,4.75,5.88,4.63,4.13,3.25,44.000,46
46,Table Tennis,3.50,2.50,4.63,4.13,5.88,4.25,1.38,1.88,8.88,6.00,43.000,47
47,Track and Field: Weights,3.25,7.88,9.13,3.00,3.13,3.00,2.25,3.63,4.00,2.88,42.125,48
48,Canoe/Kayak,6.75,5.25,5.63,3.50,2.75,3.88,3.63,3.25,3.13,4.25,42.000,49
49,Horse Racing,4.00,3.88,2.88,1.38,2.88,3.75,8.00,4.50,3.88,6.50,41.625,50
50,Golf,3.25,3.88,6.13,1.63,1.75,4.00,2.50,2.38,6.00,6.38,37.875,51
51,Cheerleading,3.63,3.63,3.38,2.25,4.13,7.50,3.63,3.38,2.50,2.25,36.250,52
52,Roller Skating,4.75,3.38,4.00,5.13,4.00,3.50,2.63,3.38,2.88,2.63,36.250,52
53,Equestrian,3.38,3.25,1.75,1.25,2.50,2.88,6.00,2.75,2.88,5.13,31.750,54
54,Archery,2.88,4.50,3.13,1.13,1.63,2.63,2.75,2.13,6.63,3.25,30.625,55
55,Curling,2.25,2.63,2.50,1.50,2.25,2.63,1.75,1.50,4.88,5.63,27.500,56
56,Bowling,2.25,2.75,3.38,1.00,1.88,2.38,1.63,1.25,4.75,4.13,25.375,57
57,Shooting,2.25,2.50,1.38,0.88,1.13,1.75,2.38,1.88,6.75,4.00,24.875,58
58,Billiards,1.00,1.00,1.75,0.75,1.00,2.63,1.63,0.75,5.25,5.75,21.500,59
59,Fishing,1.38,1.63,1.25,0.63,1.50,1.13,0.88,0.88,2.38,2.88,14.500,60

In [37]:
df5.describe()

,END,STR,PWR,SPD,AGI,FLX,NER,DUR,HAN,ANA,TOTAL,RANK
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,5.077667,5.169000,5.509167,4.815000,4.765000,4.723167,4.614833,4.612833,4.954833,4.767333,48.983333,30.400000
std,2.094217,1.715357,1.980397,2.266403,1.927273,1.704369,2.442645,1.882102,1.966328,1.576830,12.170519,17.473661
min,1.000000,1.000000,1.250000,0.630000,1.000000,1.130000,0.880000,0.750000,1.880000,2.250000,14.500000,1.000000
25%,3.500000,3.880000,4.097500,3.000000,3.437500,3.847500,2.597500,3.380000,3.130000,3.437500,44.093750,15.750000
50%,4.630000,5.190000,5.690000,5.130000,4.755000,4.750000,4.190000,4.630000,4.440000,4.250000,48.000000,30.000000
75%,6.660000,6.130000,7.130000,6.410000,6.380000,5.532500,6.532500,5.782500,6.630000,6.160000,56.031250,45.250000
max,9.630000,9.250000,9.750000,9.880000,8.250000,10.000000,9.880000,8.500000,9.250000,7.500000,72.375000,60.000000